// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Momentum.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Momentum.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260819212451_AddProjects")]
    partial class AddProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OldScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("old_scope_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<DateTimeOffset?>("SignaledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signaled_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_outbox_messages_owner_id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.ProcessedOperation", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("EffectiveOpHlc")
                        .HasColumnType("text")
                        .HasColumnName("effective_op_hlc")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_code");

                    b.HasKey("ClientId", "OperationId");

                    b.ToTable("processed_operations", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.ProjectRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("HasDeleteEditConflict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_delete_edit_conflict");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.PrimitiveCollection<List<string>>("MalformedFields")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("malformed_fields")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Pos")
                        .HasColumnType("text")
                        .HasColumnName("pos")
                        .UseCollation("C");

                    b.HasKey("EntityId");

                    b.HasIndex("OwnerId", "IsDeleted", "Pos", "EntityId")
                        .HasDatabaseName("ix_projects_owner_deleted_pos_entity");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.RefreshTokenRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash")
                        .UseCollation("C");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncClientClockRow", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.HasKey("ClientId");

                    b.ToTable("sync_client_clock", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncGcState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("GcHorizonSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("gc_horizon_seq");

                    b.HasKey("Id");

                    b.ToTable("sync_gc_state", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncOrsetRemove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_name");

                    b.HasKey("Id");

                    b.ToTable("sync_orset_removes", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncOrsetTag", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("SetName")
                        .HasColumnType("text")
                        .HasColumnName("set_name");

                    b.Property<string>("Element")
                        .HasColumnType("text")
                        .HasColumnName("element");

                    b.Property<Guid>("AddTag")
                        .HasColumnType("uuid")
                        .HasColumnName("add_tag");

                    b.Property<bool>("Cancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelled");

                    b.Property<string>("Hlc")
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.HasKey("EntityType", "EntityId", "SetName", "Element", "AddTag");

                    b.ToTable("sync_orset_tags", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncScalarMeta", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Field")
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<Guid>("WinOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("win_operation_id");

                    b.HasKey("EntityType", "EntityId", "Field");

                    b.ToTable("sync_scalar_meta", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.TaskListRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<bool>("HasDeleteEditConflict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_delete_edit_conflict");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.PrimitiveCollection<List<string>>("MalformedFields")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("malformed_fields")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Pos")
                        .HasColumnType("text")
                        .HasColumnName("pos")
                        .UseCollation("C");

                    b.HasKey("EntityId");

                    b.HasIndex("OwnerId", "IsDeleted", "Pos", "EntityId")
                        .HasDatabaseName("ix_task_lists_owner_deleted_pos_entity");

                    b.ToTable("task_lists", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.TaskRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("BoardPos")
                        .HasColumnType("text")
                        .HasColumnName("board_pos")
                        .UseCollation("C");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<bool>("HasDeleteEditConflict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_delete_edit_conflict");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("ListPos")
                        .HasColumnType("text")
                        .HasColumnName("list_pos")
                        .UseCollation("C");

                    b.PrimitiveCollection<List<string>>("MalformedFields")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("malformed_fields")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<DateTimeOffset?>("RemindAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("remind_at");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("EntityId");

                    b.HasIndex("OwnerId", "ProjectId")
                        .HasDatabaseName("ix_tasks_owner_project");

                    b.HasIndex("OwnerId", "IsDeleted", "ListPos", "EntityId")
                        .HasDatabaseName("ix_tasks_owner_deleted_listpos_entity");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.TaskTagRow", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Tag")
                        .HasColumnType("text")
                        .HasColumnName("tag")
                        .UseCollation("C");

                    b.HasKey("TaskId", "Tag");

                    b.ToTable("task_tags", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.UserRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_normalized")
                        .UseCollation("C");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email_normalized");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
