// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Momentum.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Momentum.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    partial class SyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OldScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("old_scope_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<DateTimeOffset?>("SignaledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signaled_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_outbox_messages_owner_id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.ProcessedOperation", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("EffectiveOpHlc")
                        .HasColumnType("text")
                        .HasColumnName("effective_op_hlc")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_code");

                    b.HasKey("ClientId", "OperationId");

                    b.ToTable("processed_operations", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncClientClockRow", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.HasKey("ClientId");

                    b.ToTable("sync_client_clock", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncGcState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("GcHorizonSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("gc_horizon_seq");

                    b.HasKey("Id");

                    b.ToTable("sync_gc_state", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncOrsetRemove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_name");

                    b.HasKey("Id");

                    b.ToTable("sync_orset_removes", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncOrsetTag", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("SetName")
                        .HasColumnType("text")
                        .HasColumnName("set_name");

                    b.Property<string>("Element")
                        .HasColumnType("text")
                        .HasColumnName("element");

                    b.Property<Guid>("AddTag")
                        .HasColumnType("uuid")
                        .HasColumnName("add_tag");

                    b.Property<bool>("Cancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelled");

                    b.Property<string>("Hlc")
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.HasKey("EntityType", "EntityId", "SetName", "Element", "AddTag");

                    b.ToTable("sync_orset_tags", (string)null);
                });

            modelBuilder.Entity("Momentum.Infrastructure.Persistence.SyncScalarMeta", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Field")
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("Hlc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hlc")
                        .UseCollation("C");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<Guid>("WinOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("win_operation_id");

                    b.HasKey("EntityType", "EntityId", "Field");

                    b.ToTable("sync_scalar_meta", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
