name: ci

on:
  workflow_dispatch: {}
  push:
    branches: [main]

defaults:
  run:
    working-directory: src/client

jobs:
  istemci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.44.6
      - run: flutter analyze --fatal-infos
      - run: flutter test

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.44.6
      - run: flutter build ios --no-codesign

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - run: pwsh --version
        shell: pwsh
      - run: docker info
        shell: pwsh
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - run: ./araclar/verify.ps1
        shell: pwsh
